# Generated by Django 5.1.2 on 2024-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='faixa',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('branca_cinza', 'Branca e Cinza'), ('cinza', 'Cinza'), ('cinza_preta', 'Cinza e Preta'), ('amarela_branca', 'Amarela e Branca'), ('amarela', 'Amarela'), ('amarela_preta', 'Amarela e Preta'), ('laranja_branca', 'Laranja e Branca'), ('laranja', 'Laranja'), ('laranja_preta', 'Laranja e Preta'), ('verde_branca', 'Verde e Branca'), ('verde', 'Verde'), ('verde_preta', 'Verde e Preta'), ('azul', 'Azul'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='rua',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
