# Generated by Django 4.2.16 on 2024-11-26 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_aluno_bairro_aluno_cep_aluno_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.CharField(blank=True, choices=[('infantil', 'Infantil'), ('juvenil', 'Juvenil'), ('adulto', 'Adulto')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(choices=[('infantil', 'Infantil'), ('juvenil', 'Juvenil'), ('adulto', 'Adulto')], max_length=10)),
                ('polo', models.CharField(choices=[('itatinga', 'Itatinga'), ('enseada', 'Enseada'), ('barequecaba', 'Barequeçaba'), ('boraceia', 'Boraceia')], max_length=15)),
                ('data', models.DateField(auto_now_add=True)),
                ('presente', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='cadastro.aluno')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frequencias', to='cadastro.professor')),
            ],
        ),
    ]
