# Generated by Django 4.2.16 on 2024-11-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_aluno_turma_professor_cpf_professor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.PositiveIntegerField(max_length=11, unique=True),
        ),
    ]
